### ISSUE TITLE
Make stubs for TPlayer and TServer 

### ISSUE THREAD

**Issue by xx-shitai-xx** [xtjoeytx/GServer-v2#12]
Make stubs for TPlayer + TServer and separate TLevel, TMap and TNPC from the main source into a separate class to use with the cocos2d-x client

**Comment by cnnranderson** [comment]
It appears these have been pulled out into their own classes now. We can probably consider this closed and get more granular with missing behaviors.

**Comment by xx-shitai-xx** [comment]
Ah, not quite. This issue is in relation to the `2dadventureclient` repo, that shares much of the codebase with the gserver. That project is essentially a Graal client I made from the gserver sources. I would change this to a low priority though and close it.
