### ISSUE TITLE
Segmentation fault at the end of the program

### ISSUE THREAD

**Issue by xtjoeytx** [xtjoeytx/GServer-v2#18]
Currently we are not properly shutting down V8. Some constructors are defined static in V8 binding implementations that are not being cleaned up (mainly sub-constructors for specific resources like flags etc.)

We also don't call v8::Shutdown at the end of execution as of now.

**Comment by cnnranderson** [comment]
`V8ScriptEnv` calls `v8::Shutdown` so I would assume this is resolved.

**Comment by xx-shitai-xx** [comment]
This is confirmed fixed! No crash on windows or linux builds on exit
