### ISSUE TITLE
Ability to create and read level links on serverside

### ISSUE THREAD

**Issue by tricxta** [xtjoeytx/GServer-v2#59]
This extends the recent functionality introduced (createlevel function). I imagine the workflow being something like

let newLevel = CreateLevel("test.nw");

newLevel.NewLink("dest.nw", x,y,width,height);

And then to access having access to an array member called "links" on the level object. i.e.

newLevel.links.forEach(function (link)
{
  something...
}

**Comment by xx-shitai-xx** [comment]
you missed the newX and newY parameters :)
