### ISSUE TITLE
[GS2-Parser] Functions to remove and insert array elements don't work

### ISSUE THREAD

**Issue by tricxta** [xtjoeytx/GServer-v2#63]
Functions such as remove() and delete() are meant to remove elements from an array but they don't. Not only this, but insert() also doesn't work. 
If you observe the output of this script in the f2 window of a client, this can be easily verified.

`//#CLIENTSIDE
function onCreated() {

  // Creating an Array
  this.array = {1, 2, 3};

  // Reading from an Array (Reading Element in Position 1)
  // Syntax: this.array[element_index]
  // Arrays are 0-based so in our example:
  // this.array[0] is 1
  // this.array[1] is 2
  // this.array[2] is 3
  temp.element = this.array[1];
  echo("Element: " @ temp.element);

  // Changing a Specific Element in an Array
  this.array[2] = 3.14;
  display_array();

  // Adding to an Array
  this.array.add(4);
  display_array();

  // Removing from an Array
  this.array.remove(1);
  display_array();

  // Inserting into an Array (Inserts 2.5 into Position 1)
  this.array.insert(1, 2.5);
  display_array();

  // Deleting from an Array (Deletes Element in Position 1);
  this.array.delete(1);
  display_array();

  // Combining Arrays
  temp.newarray = {5, 6, 7};
  this.array.addarray(temp.newarray);
  display_array();

  // Getting the Size / Number of Elements in Array
  temp.elements = this.array.size();
  echo("Array contains " @ temp.elements @ " elements!");
}

function display_array() {
  echo("Array: " @ this.array);
} `

**Comment by xtjoeytx** [comment]
Provide the output please
