### ISSUE TITLE
[GS2-Parser] issue with value being passed to Math.log function

### ISSUE THREAD

**Issue by tricxta** [xtjoeytx/GServer-v2#68]
Not sure if this is a duplicate of #66 , but similarly when using the function log() it requires an int be passed to it for it to work properly.

For example, the following works fine
```
temp.exp = log(100,10);
player.chat = "var = " @ temp.exp
```

However, the following doesn't work appropriately
```
temp.exp = log(player.gralats,10);
player.chat = "var = " @ temp.exp;
```

**Comment by xtjoeytx** [comment]
https://github.com/xtjoeytx/gs2-parser/commit/86ad0e115ab8b4a470cf085e60171d61dd1610ea

Verified both examples for log and pos, should be good in next gserver release
