### ISSUE TITLE
[GS2-Parser] Usage of power operator can create weird results

### ISSUE THREAD

**Issue by tricxta** [xtjoeytx/GServer-v2#83]
The following code outputs the value 531441
```
temp.test = 3^2 + 4^2;
  this.chat = "var:" @ temp.test;
```

By enclosing each power operation, it produces the correct value:
```
temp.test = (3^2) + (4^2);
  this.chat = "var:" @ temp.test;
```

**Comment by xtjoeytx** [comment]
Tested with following code:

function onCreated() {
  temp.test = 3^2 + 4^2;
  temp.test2 = (3^2) + (4^2);
  player.chat = "var:" @ temp.test @ " = " @ temp.test2;
}
